name: davidjones
favicon: null
layout_spectrum: 0.45034190989099443
typography_spectrum: 0.6837060807738453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24501624517142773
  lightness: 0.725175348110497
  saturation: 0.9537214115262032
  rhythmicContrast: 0.7727680418174714
purpose: []
